# -*- coding: utf-8 -*-
"""task4_visualization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rFstXBjQPJKlm_bVMDlvdpFoKtCi9d3
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

!find /content/drive/MyDrive -name "trends_analysed.csv"

!find /content/drive/MyDrive -name "trends_clean.csv"

import os
import shutil

os.makedirs("data", exist_ok=True)

shutil.copy(
    "/content/drive/MyDrive/trendpulse-thanusri/data/trends_clean.csv",
    "data/trends_clean.csv"
)

print("trends_clean.csv copied successfully.")

!ls data

import pandas as pd
import numpy as np

# Load the cleaned CSV created in Task 2
df = pd.read_csv("data/trends_clean.csv")

print(f"Loaded data: {df.shape}")

# Calculate average score
average_score = df["score"].mean()

# Add engagement score
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# Mark stories as popular if their score is above average
df["is_popular"] = df["score"] > average_score

# Save the analysed data
df.to_csv("data/trends_analysed.csv", index=False)

print("trends_analysed.csv created successfully.")
print(df.shape)

shutil.copy(
    "data/trends_analysed.csv",
    "/content/drive/MyDrive/trendpulse-thanusri/data/trends_analysed.csv"
)

print("trends_analysed.csv saved to Google Drive.")

import os
import shutil

os.makedirs("data", exist_ok=True)

shutil.copy(
    "/content/drive/MyDrive/trendpulse-thanusri/data/trends_analysed.csv",
    "data/trends_analysed.csv"
)

print("Task 4 data file ready.")

!ls data

import pandas as pd

df = pd.read_csv("data/trends_analysed.csv")
print(df.shape)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile task4_visualization.py
# 
# import pandas as pd
# import matplotlib.pyplot as plt
# import os
# 
# # Load the analysed data from Task 3
# df = pd.read_csv("data/trends_analysed.csv")
# 
# # Create the outputs folder if it does not exist
# os.makedirs("outputs", exist_ok=True)
# 
# print(f"Loaded {len(df)} stories.")
# 
# # --------------------------------
# # Chart 1: Top 10 Stories by Score
# # --------------------------------
# 
# # Select the 10 stories with the highest scores
# top_10 = df.nlargest(10, "score").copy()
# 
# # Shorten titles longer than 50 characters
# top_10["short_title"] = top_10["title"].apply(
#     lambda title: title[:50] + "..." if len(title) > 50 else title
# )
# 
# # Create a horizontal bar chart
# plt.figure(figsize=(10, 6))
# plt.barh(top_10["short_title"], top_10["score"])
# 
# plt.title("Top 10 Stories by Score")
# plt.xlabel("Score")
# plt.ylabel("Story Title")
# 
# # Show the highest score at the top
# plt.gca().invert_yaxis()
# 
# # Save the chart before displaying it
# plt.tight_layout()
# plt.savefig("outputs/chart1_top_stories.png")
# plt.show()
# 
# print("Chart 1 saved successfully.")

!python task4_visualization.py

!ls outputs

# Commented out IPython magic to ensure Python compatibility.
# %%writefile task4_visualization.py
# 
# import pandas as pd
# import matplotlib.pyplot as plt
# import os
# 
# # Load the analysed data from Task 3
# df = pd.read_csv("data/trends_analysed.csv")
# 
# # Create the outputs folder if it does not exist
# os.makedirs("outputs", exist_ok=True)
# 
# print(f"Loaded {len(df)} stories.")
# 
# # --------------------------------
# # Chart 1: Top 10 Stories by Score
# # --------------------------------
# 
# # Select the 10 stories with the highest scores
# top_10 = df.nlargest(10, "score").copy()
# 
# # Shorten titles longer than 50 characters
# top_10["short_title"] = top_10["title"].apply(
#     lambda title: title[:50] + "..." if len(title) > 50 else title
# )
# 
# plt.figure(figsize=(10, 6))
# plt.barh(top_10["short_title"], top_10["score"])
# 
# plt.title("Top 10 Stories by Score")
# plt.xlabel("Score")
# plt.ylabel("Story Title")
# 
# # Show the highest score at the top
# plt.gca().invert_yaxis()
# 
# plt.tight_layout()
# plt.savefig("outputs/chart1_top_stories.png")
# plt.show()
# 
# print("Chart 1 saved successfully.")
# 
# 
# # --------------------------------
# # Chart 2: Stories per Category
# # --------------------------------
# 
# # Count the number of stories in each category
# category_counts = df["category"].value_counts()
# 
# plt.figure(figsize=(8, 6))
# 
# # Create a bar chart with a different colour for each category
# plt.bar(
#     category_counts.index,
#     category_counts.values,
#     color=plt.cm.tab10(range(len(category_counts)))
# )
# 
# plt.title("Stories per Category")
# plt.xlabel("Category")
# plt.ylabel("Number of Stories")
# 
# plt.tight_layout()
# plt.savefig("outputs/chart2_categories.png")
# plt.show()
# 
# print("Chart 2 saved successfully.")

!python task4_visualization.py

!ls outputs

# Commented out IPython magic to ensure Python compatibility.
# %%writefile task4_visualization.py
# 
# import pandas as pd
# import matplotlib.pyplot as plt
# import os
# 
# # Load the analysed data from Task 3
# df = pd.read_csv("data/trends_analysed.csv")
# 
# # Create the outputs folder if it does not exist
# os.makedirs("outputs", exist_ok=True)
# 
# print(f"Loaded {len(df)} stories.")
# 
# # --------------------------------
# # Chart 1: Top 10 Stories by Score
# # --------------------------------
# 
# # Select the 10 stories with the highest scores
# top_10 = df.nlargest(10, "score").copy()
# 
# # Shorten titles longer than 50 characters
# top_10["short_title"] = top_10["title"].apply(
#     lambda title: title[:50] + "..." if len(title) > 50 else title
# )
# 
# plt.figure(figsize=(10, 6))
# plt.barh(top_10["short_title"], top_10["score"])
# 
# plt.title("Top 10 Stories by Score")
# plt.xlabel("Score")
# plt.ylabel("Story Title")
# 
# # Show the highest score at the top
# plt.gca().invert_yaxis()
# 
# plt.tight_layout()
# plt.savefig("outputs/chart1_top_stories.png")
# plt.show()
# 
# print("Chart 1 saved successfully.")
# 
# 
# # --------------------------------
# # Chart 2: Stories per Category
# # --------------------------------
# 
# # Count the number of stories in each category
# category_counts = df["category"].value_counts()
# 
# plt.figure(figsize=(8, 6))
# 
# # Give each category bar a different colour
# plt.bar(
#     category_counts.index,
#     category_counts.values,
#     color=plt.cm.tab10(range(len(category_counts)))
# )
# 
# plt.title("Stories per Category")
# plt.xlabel("Category")
# plt.ylabel("Number of Stories")
# 
# plt.tight_layout()
# plt.savefig("outputs/chart2_categories.png")
# plt.show()
# 
# print("Chart 2 saved successfully.")
# 
# 
# # --------------------------------
# # Chart 3: Score vs Comments
# # --------------------------------
# 
# # Separate popular and non-popular stories
# popular = df[df["is_popular"] == True]
# not_popular = df[df["is_popular"] == False]
# 
# plt.figure(figsize=(10, 6))
# 
# # Plot popular stories
# plt.scatter(
#     popular["score"],
#     popular["num_comments"],
#     label="Popular",
#     alpha=0.7
# )
# 
# # Plot non-popular stories
# plt.scatter(
#     not_popular["score"],
#     not_popular["num_comments"],
#     label="Not Popular",
#     alpha=0.7
# )
# 
# plt.title("Score vs Comments")
# plt.xlabel("Score")
# plt.ylabel("Number of Comments")
# plt.legend()
# 
# plt.tight_layout()
# plt.savefig("outputs/chart3_scatter.png")
# plt.show()
# 
# print("Chart 3 saved successfully.")

!python task4_visualization.py

!ls outputs

popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

!ls outputs

# Commented out IPython magic to ensure Python compatibility.
# %%writefile task4_visualization.py
# 
# import pandas as pd
# import matplotlib.pyplot as plt
# import os
# 
# # Load the analysed data from Task 3
# df = pd.read_csv("data/trends_analysed.csv")
# 
# # Create the outputs folder if it does not exist
# os.makedirs("outputs", exist_ok=True)
# 
# print(f"Loaded {len(df)} stories.")
# 
# # --------------------------------
# # Chart 1: Top 10 Stories by Score
# # --------------------------------
# 
# top_10 = df.nlargest(10, "score").copy()
# 
# # Shorten titles longer than 50 characters
# top_10["short_title"] = top_10["title"].apply(
#     lambda title: title[:50] + "..." if len(title) > 50 else title
# )
# 
# plt.figure(figsize=(10, 6))
# plt.barh(top_10["short_title"], top_10["score"])
# 
# plt.title("Top 10 Stories by Score")
# plt.xlabel("Score")
# plt.ylabel("Story Title")
# 
# plt.gca().invert_yaxis()
# 
# plt.tight_layout()
# plt.savefig("outputs/chart1_top_stories.png")
# plt.show()
# 
# print("Chart 1 saved successfully.")
# 
# 
# # --------------------------------
# # Chart 2: Stories per Category
# # --------------------------------
# 
# category_counts = df["category"].value_counts()
# 
# plt.figure(figsize=(8, 6))
# 
# plt.bar(
#     category_counts.index,
#     category_counts.values,
#     color=plt.cm.tab10(range(len(category_counts)))
# )
# 
# plt.title("Stories per Category")
# plt.xlabel("Category")
# plt.ylabel("Number of Stories")
# 
# plt.tight_layout()
# plt.savefig("outputs/chart2_categories.png")
# plt.show()
# 
# print("Chart 2 saved successfully.")
# 
# 
# # --------------------------------
# # Chart 3: Score vs Comments
# # --------------------------------
# 
# popular = df[df["is_popular"] == True]
# not_popular = df[df["is_popular"] == False]
# 
# plt.figure(figsize=(10, 6))
# 
# plt.scatter(
#     popular["score"],
#     popular["num_comments"],
#     label="Popular",
#     alpha=0.7
# )
# 
# plt.scatter(
#     not_popular["score"],
#     not_popular["num_comments"],
#     label="Not Popular",
#     alpha=0.7
# )
# 
# plt.title("Score vs Comments")
# plt.xlabel("Score")
# plt.ylabel("Number of Comments")
# plt.legend()
# 
# plt.tight_layout()
# plt.savefig("outputs/chart3_scatter.png")
# plt.show()
# 
# print("Chart 3 saved successfully.")
# 
# 
# # --------------------------------
# # Bonus: TrendPulse Dashboard
# # --------------------------------
# 
# fig, axes = plt.subplots(2, 2, figsize=(16, 12))
# 
# # Dashboard Chart 1
# axes[0, 0].barh(
#     top_10["short_title"],
#     top_10["score"]
# )
# 
# axes[0, 0].set_title("Top 10 Stories by Score")
# axes[0, 0].set_xlabel("Score")
# axes[0, 0].set_ylabel("Story Title")
# axes[0, 0].invert_yaxis()
# 
# # Dashboard Chart 2
# axes[0, 1].bar(
#     category_counts.index,
#     category_counts.values,
#     color=plt.cm.tab10(range(len(category_counts)))
# )
# 
# axes[0, 1].set_title("Stories per Category")
# axes[0, 1].set_xlabel("Category")
# axes[0, 1].set_ylabel("Number of Stories")
# 
# # Dashboard Chart 3
# axes[1, 0].scatter(
#     popular["score"],
#     popular["num_comments"],
#     label="Popular",
#     alpha=0.7
# )
# 
# axes[1, 0].scatter(
#     not_popular["score"],
#     not_popular["num_comments"],
#     label="Not Popular",
#     alpha=0.7
# )
# 
# axes[1, 0].set_title("Score vs Comments")
# axes[1, 0].set_xlabel("Score")
# axes[1, 0].set_ylabel("Number of Comments")
# axes[1, 0].legend()
# 
# # Hide the unused fourth subplot
# axes[1, 1].axis("off")
# 
# # Overall dashboard title
# fig.suptitle("TrendPulse Dashboard", fontsize=20)
# 
# plt.tight_layout(rect=[0, 0, 1, 0.96])
# 
# # Save dashboard
# plt.savefig("outputs/dashboard.png")
# plt.show()
# 
# print("Dashboard saved successfully.")

!python task4_visualization.py

!ls outputs

