# -*- coding: utf-8 -*-
"""task2_data_processing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1ptAvz_OPzz880QhCkZVBubAIxaieP7
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil

os.makedirs("data", exist_ok=True)

shutil.copy(
    "/content/drive/MyDrive/trendpulse-thanusri/data/trends_20260929.json",
    "data/trends_20260929.json"
)

print("JSON file copied to Task 2 environment.")

!ls data

!python task2_data_processing.py

!ls data

import pandas as pd
import glob

# Find the JSON file created by Task 1
json_files = glob.glob("data/trends_*.json")

if not json_files:
    print("JSON file not found. Please run Task 1 first.")
else:
    # Select the JSON file
    json_file = json_files[0]

    # Load JSON data into a Pandas DataFrame
    df = pd.read_json(json_file)

    print(f"Loaded {len(df)} stories from {json_file}")

    # Remove duplicate stories based on post_id
    df = df.drop_duplicates(subset="post_id")
    print(f"After removing duplicates: {len(df)}")

    # Remove rows where post_id, title, or score is missing
    df = df.dropna(subset=["post_id", "title", "score"])
    print(f"After removing nulls: {len(df)}")

    # Convert score and num_comments to numeric values
    df["score"] = pd.to_numeric(df["score"], errors="coerce")
    df["num_comments"] = pd.to_numeric(df["num_comments"], errors="coerce")

    # Remove rows where conversion failed
    df = df.dropna(subset=["score", "num_comments"])

    # Convert score and num_comments to integers
    df["score"] = df["score"].astype(int)
    df["num_comments"] = df["num_comments"].astype(int)

    # Remove stories with score less than 5
    df = df[df["score"] >= 5]
    print(f"After removing low scores: {len(df)}")

    # Remove extra spaces from titles
    df["title"] = df["title"].str.strip()

    # Save the cleaned data as CSV
    output_file = "data/trends_clean.csv"
    df.to_csv(output_file, index=False)

    print(f"\nSaved {len(df)} rows to {output_file}")

    # Print the number of stories per category
    print("\nStories per category:")
    print(df["category"].value_counts())