# -*- coding: utf-8 -*-
"""task3_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5oooPpRpqs6RQazk-JUwGqC5t4JrnNk
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile task3_analysis.py
# 
# import pandas as pd
# import numpy as np
# 
# # Load the cleaned CSV created in Task 2
# df = pd.read_csv("data/trends_clean.csv")
# 
# print(f"Loaded data: {df.shape}")
# 
# # Display the first 5 rows
# print("\nFirst 5 rows:")
# print(df.head())
# 
# # Calculate average score and average comments
# average_score = df["score"].mean()
# average_comments = df["num_comments"].mean()
# 
# print(f"\nAverage score   : {average_score:.2f}")
# print(f"Average comments: {average_comments:.2f}")
# 
# 
# # ---------------------------------------------------------
# # NumPy Statistics
# # ---------------------------------------------------------
# 
# # Convert score column to a NumPy array
# scores = df["score"].to_numpy()
# 
# # Calculate mean, median and standard deviation using NumPy
# mean_score = np.mean(scores)
# median_score = np.median(scores)
# std_score = np.std(scores)
# 
# # Find maximum and minimum scores
# max_score = np.max(scores)
# min_score = np.min(scores)
# 
# print("\n--- NumPy Stats ---")
# print(f"Mean score   : {mean_score:.2f}")
# print(f"Median score : {median_score:.2f}")
# print(f"Std deviation: {std_score:.2f}")
# print(f"Max score    : {max_score}")
# print(f"Min score    : {min_score}")
# 
# 
# # ---------------------------------------------------------
# # Category Analysis
# # ---------------------------------------------------------
# 
# # Count the number of stories in each category
# category_counts = df["category"].value_counts()
# 
# most_common_category = category_counts.idxmax()
# most_common_count = category_counts.max()
# 
# print(
#     f"\nMost stories in: "
#     f"{most_common_category} ({most_common_count} stories)"
# )
# 
# 
# # ---------------------------------------------------------
# # Most Commented Story
# # ---------------------------------------------------------
# 
# # Find the row containing the highest number of comments
# most_commented = df.loc[df["num_comments"].idxmax()]
# 
# print(
#     f'\nMost commented story: '
#     f'"{most_commented["title"]}" '
#     f'— {most_commented["num_comments"]} comments'
# )
# 
# 
# # ---------------------------------------------------------
# # Add New Columns
# # ---------------------------------------------------------
# 
# # Engagement measures comments relative to the score
# df["engagement"] = df["num_comments"] / (df["score"] + 1)
# 
# # Mark stories whose score is above the average score
# df["is_popular"] = df["score"] > average_score
# 
# 
# # ---------------------------------------------------------
# # Save the analysed data
# # ---------------------------------------------------------
# 
# output_file = "data/trends_analysed.csv"
# 
# df.to_csv(output_file, index=False)
# 
# print(f"\nSaved to {output_file}")

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil

os.makedirs("data", exist_ok=True)

shutil.copy(
    "/content/drive/MyDrive/trendpulse-thanusri/data/trends_clean.csv",
    "data/trends_clean.csv"
)

print("trends_clean.csv copied successfully.")

!python task3_analysis.py

import pandas as pd

df = pd.read_csv("data/trends_analysed.csv")
print(df.shape)
print(df.columns.tolist())

