# -*- coding: utf-8 -*-
"""task1_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5ZQFtLuZH2ZjqOuRoclGx3oqWdxuXdV
"""

import requests
import time
import json
import os
from datetime import datetime


# =========================================================
# HACKER NEWS API
# =========================================================

TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

headers = {
    "User-Agent": "TrendPulse/1.0"
}


# =========================================================
# REQUIREMENTS
# =========================================================

MIN_TOTAL_STORIES = 100
MAX_PER_CATEGORY = 25

categories = {

    "technology": [
        "ai", "artificial intelligence", "software",
        "tech", "technology", "computer", "programming",
        "code", "developer", "data", "cloud", "api",
        "gpu", "llm", "machine learning", "open source",
        "linux", "python", "javascript", "github",
        "database", "cybersecurity", "robot", "robotics"
    ],

    "worldnews": [
        "war", "government", "country", "president",
        "election", "climate", "attack", "global",
        "world", "international", "minister", "politics",
        "political", "nation", "military", "ukraine",
        "russia", "china", "india", "europe", "israel",
        "iran", "trump", "congress", "parliament",
        "law", "policy", "sanctions", "united states"
    ],

    "sports": [
        "nfl", "nba", "fifa", "sport", "sports",
        "football", "soccer", "basketball", "baseball",
        "cricket", "tennis", "golf", "player", "team",
        "league", "championship", "cup", "match",
        "game", "olympic", "olympics", "athlete",
        "coach", "world cup", "formula 1", "f1"
    ],

    "science": [
        "research", "study", "science", "scientific",
        "space", "physics", "biology", "discovery",
        "nasa", "genome", "genetics", "chemistry",
        "astronomy", "planet", "earth", "moon",
        "mars", "quantum", "experiment", "laboratory",
        "medical", "health", "climate", "species",
        "evolution", "telescope", "asteroid"
    ],

    "entertainment": [
        "movie", "film", "music", "netflix",
        "game", "games", "book", "show", "award",
        "streaming", "actor", "actress", "director",
        "tv", "television", "series", "album",
        "song", "concert", "hollywood", "youtube",
        "podcast", "anime", "video game", "playstation",
        "xbox", "nintendo"
    ]
}


# =========================================================
# STEP 1: FETCH TOP STORY IDS
# =========================================================

try:

    response = requests.get(
        TOP_STORIES_URL,
        headers=headers,
        timeout=10
    )

    response.raise_for_status()

    # Fetch more than 500 IDs so we have enough candidates
    story_ids = response.json()[:1000]

    print(f"Fetched {len(story_ids)} story IDs.")

except requests.RequestException as error:

    print(f"Failed to fetch story IDs: {error}")
    raise SystemExit


# =========================================================
# STEP 2: FETCH STORY DETAILS
# =========================================================

stories = []

print("\nFetching story details...")

for index, story_id in enumerate(story_ids, start=1):

    try:

        response = requests.get(
            ITEM_URL.format(story_id),
            headers=headers,
            timeout=10
        )

        response.raise_for_status()

        story = response.json()

        if story and story.get("title"):

            stories.append(story)

    except requests.RequestException as error:

        print(
            f"Failed to fetch story {story_id}: {error}"
        )

        continue

    # Progress message every 100 stories
    if index % 100 == 0:

        print(
            f"Fetched details for {index}/{len(story_ids)} stories..."
        )


print(
    f"\nSuccessfully fetched {len(stories)} stories."
)


# =========================================================
# STEP 3: COLLECT STORIES BY CATEGORY
# =========================================================

collected_stories = []

# Keep track of story IDs already used
used_story_ids = set()


for category, keywords in categories.items():

    print(f"\nCollecting {category} stories...")

    category_count = 0

    for story in stories:

        # Stop at 25 stories for this category
        if category_count >= MAX_PER_CATEGORY:
            break

        story_id = story.get("id")

        # Avoid using the same story in multiple categories
        if story_id in used_story_ids:
            continue

        title = story.get("title", "")
        title_lower = title.lower()

        # Check keyword match
        matched = False

        for keyword in keywords:

            if keyword.lower() in title_lower:

                matched = True
                break

        if not matched:
            continue

        # Create required record
        record = {
            "post_id": story_id,
            "title": title,
            "category": category,
            "score": story.get("score", 0),
            "num_comments": story.get("descendants", 0),
            "author": story.get("by", "unknown"),
            "collected_at": datetime.now().isoformat()
        }

        collected_stories.append(record)

        used_story_ids.add(story_id)

        category_count += 1

        print(
            f"{category}: "
            f"{category_count}/{MAX_PER_CATEGORY}"
        )

    if category_count < MAX_PER_CATEGORY:

        print(
            f"Only {category_count} stories found "
            f"for {category}."
        )

    time.sleep(1)


# =========================================================
# STEP 4: CHECK TOTAL
# =========================================================

print("\n----------------------------------------")

print(
    f"Total stories collected: "
    f"{len(collected_stories)}"
)

print("----------------------------------------")


# =========================================================
# STEP 5: CREATE DATA FOLDER
# =========================================================

os.makedirs("data", exist_ok=True)


# =========================================================
# STEP 6: CREATE OUTPUT FILE
# =========================================================

date_string = datetime.now().strftime("%Y%m%d")

output_file = f"data/trends_{date_string}.json"


# =========================================================
# STEP 7: SAVE JSON
# =========================================================

with open(
    output_file,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        collected_stories,
        file,
        indent=4,
        ensure_ascii=False
    )


# =========================================================
# STEP 8: DISPLAY RESULTS
# =========================================================

print("\nCollection completed.")

print(
    f"Collected {len(collected_stories)} stories."
)

print(
    f"Saved to {output_file}"
)


print("\nCategory totals:")

for category in categories:

    count = sum(
        1
        for story in collected_stories
        if story["category"] == category
    )

    print(
        f"{category}: {count}"
    )


# =========================================================
# FINAL CHECK
# =========================================================

if len(collected_stories) >= MIN_TOTAL_STORIES:

    print(
        f"\nSUCCESS: {len(collected_stories)} "
        f"stories collected."
    )

else:

    print(
        f"\nWARNING: Only {len(collected_stories)} "
        f"stories collected."
    )

    print(
        "Consider increasing the number of "
        "Hacker News story IDs."
    )